description: Fred Arnoux, front-end web developer based in Paris.

author:
  name:       Fred Arnoux
  email:      fred@farnoux.com
  twitter:    farnoux
  github:     farnoux
  linkedin:   farnoux

pygments:   true
