description: Copsy, Deferred-driven validation plugin for jQuery.

author:
  name:       Fred Arnoux
  email:      fred@farnoux.com
  twitter:    farnoux
  github:     farnoux
  linkedin:   farnoux

pygments:   true
